### ISSUE TITLE
support doc id's in write

### ISSUE THREAD

**Issue by henridf** [juttle/juttle-elastic-adapter#32]
I'm using document id's and would like to be able to specify them when doing `write elastic`. But the current es-adapter doesn't specify doc id's when inserting into elastic. 

How about saying that if a point (is that still what they are called?) has a field `_id`, then that is used as the document id when inserting into elastic. And/or make the name of that field an option that can be passed to `write`.

**Comment by demmer** [comment]
I certainly support the idea of allowing the doc ids to be specified and although I like the convenience of automatically doing so for a field called `_id`, it would break symmetry with `read` since those points wouldn't presumably have the id in a field.

How about we have an option `-idField` supported by both `read` and `write`? On the read side it would populate the field with the document ids and on the write side it would (obviously) use that id for the document?

**Comment by henridf** [comment]
> it would break symmetry with read since those points wouldn't presumably have the id in a field.

I don't understand this - why wouldn't points being read from ES have an id field already?

**Comment by davidvgalbraith** [comment]
The `_id` field is not stored with the `_source`, which is all `read` currently looks at when returning points. 

`read -idField` would add the `_id` of each document to its `_source` in the `idField` to get the final Juttle point. `write -idField` would take the `idField` of each input Juttle point and use it as the `_id` field in Elasticsearch. 

If `write` were to use a default `idField` of "`_id` when present", then the symmetric thing for `read` to do would be to have a default `idField` of `_id`. In default Elasticsearch setups, the `_id` is a meaningless auto-generated string, so adding it to all the points by default would be distracting and confusing. Since we don't want to distract and confuse, and we don't want read/write asymmetry, we'll require the `-idField` option to get any `_id`-aware behavior.

**Comment by henridf** [comment]
i see, makes sense.
