### ISSUE TITLE
Read filter on time should work, not be a silent empty result

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-elastic-adapter#83]
If I give `read elastic` a filter expression that matches on time, the result is an empty set without error:

```
juttle> read elastic -from :0: -to :now: time = :2016-02-03T03:03:03.000Z:
└───────────┴───────────┘
```

This doesn't seem right, as adding an explicit filter works fine:

```
juttle> read elastic -from :0: -to :now: | filter time = :2016-02-03T03:03:03.000Z:
┌────────────────────────────────────┬────────────┬──────────┐
│ time                               │ name       │ value    │
├────────────────────────────────────┼────────────┼──────────┤
│ 2016-02-03T03:03:03.000Z           │ got*star   │ 42       │
└────────────────────────────────────┴────────────┴──────────┘
```

So the in-read time filter should either work properly, or (more likely) output an error along the lines of "Filter expression on time is not supported in read, use -from/-to options, or the filter processor".

**Comment by davidvgalbraith** [comment]
This will work. It requires https://github.com/juttle/juttle-elastic-adapter/pull/103 though which requires a new Juttle release.

**Comment by demmer** [comment]
When this has come up before we've always decided that explicit filtering on time is not a good thing to do since it overlaps with the `-from` and `-to` processing.

So my instinct is that we should go with the second suggestion in the description -- namely to reject any filters that include time.

Actually come to think of it, this should be something that we do in the semantic pass of the juttle core rather than in each adapter separately. @dmajda @davidvgalbraith what do you guys think?

**Comment by davidvgalbraith** [comment]
Great!

**Comment by dmajda** [comment]
> Actually come to think of it, this should be something that we do in the semantic pass of the juttle core rather than in each adapter separately. @dmajda @davidvgalbraith what do you guys think?

+1, the most appropriate place for the check seems to be `StaticFilterChecker` (nothing against the semantic pass, I just think it’s better to clump all the filter checks together)
